// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mgmt.proto

package mgmt_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentType int32

const (
	// Protoc says this has to be here
	ContentType_Zero ContentType = 0
	// Services
	ContentType_ListServicesRequestType  ContentType = 10001
	ContentType_ListServicesResponseType ContentType = 10002
	ContentType_CreateServiceRequestType ContentType = 10003
	ContentType_RemoveServiceRequestType ContentType = 10005
	ContentType_GetServiceRequestType    ContentType = 10006
	ContentType_GetServiceResponseType   ContentType = 10007
	// Service Endpoints
	ContentType_CreateEndpointRequestType ContentType = 10050
	ContentType_RemoveEndpointRequestType ContentType = 10051
	ContentType_ListEndpointsRequestType  ContentType = 10052
	ContentType_ListEndpointsResponseType ContentType = 10053
	ContentType_GetEndpointRequestType    ContentType = 10054
	ContentType_GetEndpointResponseType   ContentType = 10055
	// Routers
	ContentType_ListRoutersRequestType  ContentType = 10010
	ContentType_ListRoutersResponseType ContentType = 10011
	ContentType_CreateRouterRequestType ContentType = 10012
	ContentType_RemoveRouterRequestType ContentType = 10013
	// Links
	ContentType_ListLinksRequestType   ContentType = 10020
	ContentType_ListLinksResponseType  ContentType = 10021
	ContentType_SetLinkCostRequestType ContentType = 10022
	ContentType_SetLinkDownRequestType ContentType = 10023
	// Sessions
	ContentType_ListSessionsRequestType  ContentType = 10030
	ContentType_ListSessionsResponseType ContentType = 10031
	ContentType_RemoveSessionRequestType ContentType = 10032
	// Streams
	ContentType_StreamMetricsRequestType       ContentType = 10040
	ContentType_StreamMetricsEventType         ContentType = 10041
	ContentType_StreamSessionsRequestType      ContentType = 10042
	ContentType_StreamSessionsEventType        ContentType = 10043
	ContentType_TogglePipeTracesRequestType    ContentType = 10044
	ContentType_ToggleSessionTracesRequestType ContentType = 10045
	ContentType_StreamTracesRequestType        ContentType = 10046
	ContentType_StreamTracesEventType          ContentType = 10047
	// Inspect
	ContentType_InspectRequestType  ContentType = 10048
	ContentType_InspectResponseType ContentType = 10049
)

var ContentType_name = map[int32]string{
	0:     "Zero",
	10001: "ListServicesRequestType",
	10002: "ListServicesResponseType",
	10003: "CreateServiceRequestType",
	10005: "RemoveServiceRequestType",
	10006: "GetServiceRequestType",
	10007: "GetServiceResponseType",
	10050: "CreateEndpointRequestType",
	10051: "RemoveEndpointRequestType",
	10052: "ListEndpointsRequestType",
	10053: "ListEndpointsResponseType",
	10054: "GetEndpointRequestType",
	10055: "GetEndpointResponseType",
	10010: "ListRoutersRequestType",
	10011: "ListRoutersResponseType",
	10012: "CreateRouterRequestType",
	10013: "RemoveRouterRequestType",
	10020: "ListLinksRequestType",
	10021: "ListLinksResponseType",
	10022: "SetLinkCostRequestType",
	10023: "SetLinkDownRequestType",
	10030: "ListSessionsRequestType",
	10031: "ListSessionsResponseType",
	10032: "RemoveSessionRequestType",
	10040: "StreamMetricsRequestType",
	10041: "StreamMetricsEventType",
	10042: "StreamSessionsRequestType",
	10043: "StreamSessionsEventType",
	10044: "TogglePipeTracesRequestType",
	10045: "ToggleSessionTracesRequestType",
	10046: "StreamTracesRequestType",
	10047: "StreamTracesEventType",
	10048: "InspectRequestType",
	10049: "InspectResponseType",
}

var ContentType_value = map[string]int32{
	"Zero": 0,
	"ListServicesRequestType":        10001,
	"ListServicesResponseType":       10002,
	"CreateServiceRequestType":       10003,
	"RemoveServiceRequestType":       10005,
	"GetServiceRequestType":          10006,
	"GetServiceResponseType":         10007,
	"CreateEndpointRequestType":      10050,
	"RemoveEndpointRequestType":      10051,
	"ListEndpointsRequestType":       10052,
	"ListEndpointsResponseType":      10053,
	"GetEndpointRequestType":         10054,
	"GetEndpointResponseType":        10055,
	"ListRoutersRequestType":         10010,
	"ListRoutersResponseType":        10011,
	"CreateRouterRequestType":        10012,
	"RemoveRouterRequestType":        10013,
	"ListLinksRequestType":           10020,
	"ListLinksResponseType":          10021,
	"SetLinkCostRequestType":         10022,
	"SetLinkDownRequestType":         10023,
	"ListSessionsRequestType":        10030,
	"ListSessionsResponseType":       10031,
	"RemoveSessionRequestType":       10032,
	"StreamMetricsRequestType":       10040,
	"StreamMetricsEventType":         10041,
	"StreamSessionsRequestType":      10042,
	"StreamSessionsEventType":        10043,
	"TogglePipeTracesRequestType":    10044,
	"ToggleSessionTracesRequestType": 10045,
	"StreamTracesRequestType":        10046,
	"StreamTracesEventType":          10047,
	"InspectRequestType":             10048,
	"InspectResponseType":            10049,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}

func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{0}
}

type StreamSessionEventType int32

const (
	StreamSessionEventType_SessionCreated StreamSessionEventType = 0
	StreamSessionEventType_SessionDeleted StreamSessionEventType = 1
	StreamSessionEventType_SessionPresent StreamSessionEventType = 2
	StreamSessionEventType_CircuitUpdated StreamSessionEventType = 3
)

var StreamSessionEventType_name = map[int32]string{
	0: "SessionCreated",
	1: "SessionDeleted",
	2: "SessionPresent",
	3: "CircuitUpdated",
}

var StreamSessionEventType_value = map[string]int32{
	"SessionCreated": 0,
	"SessionDeleted": 1,
	"SessionPresent": 2,
	"CircuitUpdated": 3,
}

func (x StreamSessionEventType) String() string {
	return proto.EnumName(StreamSessionEventType_name, int32(x))
}

func (StreamSessionEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{1}
}

type TraceFilterType int32

const (
	TraceFilterType_EXCLUDE TraceFilterType = 0
	TraceFilterType_INCLUDE TraceFilterType = 1
)

var TraceFilterType_name = map[int32]string{
	0: "EXCLUDE",
	1: "INCLUDE",
}

var TraceFilterType_value = map[string]int32{
	"EXCLUDE": 0,
	"INCLUDE": 1,
}

func (x TraceFilterType) String() string {
	return proto.EnumName(TraceFilterType_name, int32(x))
}

func (TraceFilterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{2}
}

type Service struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EndpointStrategy     string      `protobuf:"bytes,2,opt,name=endpointStrategy,proto3" json:"endpointStrategy,omitempty"`
	Endpoints            []*Endpoint `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetEndpointStrategy() string {
	if m != nil {
		return m.EndpointStrategy
	}
	return ""
}

func (m *Service) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type Endpoint struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId            string               `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	RouterId             string               `protobuf:"bytes,3,opt,name=routerId,proto3" json:"routerId,omitempty"`
	Binding              string               `protobuf:"bytes,4,opt,name=binding,proto3" json:"binding,omitempty"`
	Address              string               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	PeerData             map[uint32][]byte    `protobuf:"bytes,7,rep,name=peerData,proto3" json:"peerData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{1}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Endpoint) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Endpoint) GetRouterId() string {
	if m != nil {
		return m.RouterId
	}
	return ""
}

func (m *Endpoint) GetBinding() string {
	if m != nil {
		return m.Binding
	}
	return ""
}

func (m *Endpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Endpoint) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Endpoint) GetPeerData() map[uint32][]byte {
	if m != nil {
		return m.PeerData
	}
	return nil
}

type ListServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{2}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

type ListServicesResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{3}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type CreateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceRequest) Reset()         { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()    {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{4}
}

func (m *CreateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceRequest.Unmarshal(m, b)
}
func (m *CreateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceRequest.Merge(m, src)
}
func (m *CreateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceRequest.Size(m)
}
func (m *CreateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceRequest proto.InternalMessageInfo

func (m *CreateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type RemoveServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveServiceRequest) Reset()         { *m = RemoveServiceRequest{} }
func (m *RemoveServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveServiceRequest) ProtoMessage()    {}
func (*RemoveServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{5}
}

func (m *RemoveServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveServiceRequest.Unmarshal(m, b)
}
func (m *RemoveServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveServiceRequest.Marshal(b, m, deterministic)
}
func (m *RemoveServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveServiceRequest.Merge(m, src)
}
func (m *RemoveServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveServiceRequest.Size(m)
}
func (m *RemoveServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveServiceRequest proto.InternalMessageInfo

func (m *RemoveServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type GetServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceRequest) Reset()         { *m = GetServiceRequest{} }
func (m *GetServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceRequest) ProtoMessage()    {}
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{6}
}

func (m *GetServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceRequest.Unmarshal(m, b)
}
func (m *GetServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceRequest.Merge(m, src)
}
func (m *GetServiceRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceRequest.Size(m)
}
func (m *GetServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceRequest proto.InternalMessageInfo

func (m *GetServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type GetServiceResponse struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceResponse) Reset()         { *m = GetServiceResponse{} }
func (m *GetServiceResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceResponse) ProtoMessage()    {}
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{7}
}

func (m *GetServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceResponse.Unmarshal(m, b)
}
func (m *GetServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceResponse.Merge(m, src)
}
func (m *GetServiceResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceResponse.Size(m)
}
func (m *GetServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceResponse proto.InternalMessageInfo

func (m *GetServiceResponse) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

// service endpoints
type ListEndpointsRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	RouterId             string   `protobuf:"bytes,2,opt,name=routerId,proto3" json:"routerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEndpointsRequest) Reset()         { *m = ListEndpointsRequest{} }
func (m *ListEndpointsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEndpointsRequest) ProtoMessage()    {}
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{8}
}

func (m *ListEndpointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEndpointsRequest.Unmarshal(m, b)
}
func (m *ListEndpointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEndpointsRequest.Marshal(b, m, deterministic)
}
func (m *ListEndpointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEndpointsRequest.Merge(m, src)
}
func (m *ListEndpointsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEndpointsRequest.Size(m)
}
func (m *ListEndpointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEndpointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEndpointsRequest proto.InternalMessageInfo

func (m *ListEndpointsRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ListEndpointsRequest) GetRouterId() string {
	if m != nil {
		return m.RouterId
	}
	return ""
}

type ListEndpointsResponse struct {
	Endpoints            []*Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListEndpointsResponse) Reset()         { *m = ListEndpointsResponse{} }
func (m *ListEndpointsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEndpointsResponse) ProtoMessage()    {}
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{9}
}

func (m *ListEndpointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEndpointsResponse.Unmarshal(m, b)
}
func (m *ListEndpointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEndpointsResponse.Marshal(b, m, deterministic)
}
func (m *ListEndpointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEndpointsResponse.Merge(m, src)
}
func (m *ListEndpointsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEndpointsResponse.Size(m)
}
func (m *ListEndpointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEndpointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEndpointsResponse proto.InternalMessageInfo

func (m *ListEndpointsResponse) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type CreateEndpointRequest struct {
	Endpoint             *Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateEndpointRequest) Reset()         { *m = CreateEndpointRequest{} }
func (m *CreateEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEndpointRequest) ProtoMessage()    {}
func (*CreateEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{10}
}

func (m *CreateEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEndpointRequest.Unmarshal(m, b)
}
func (m *CreateEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEndpointRequest.Marshal(b, m, deterministic)
}
func (m *CreateEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEndpointRequest.Merge(m, src)
}
func (m *CreateEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEndpointRequest.Size(m)
}
func (m *CreateEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEndpointRequest proto.InternalMessageInfo

func (m *CreateEndpointRequest) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type RemoveEndpointRequest struct {
	EndpointId           string   `protobuf:"bytes,1,opt,name=endpointId,proto3" json:"endpointId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEndpointRequest) Reset()         { *m = RemoveEndpointRequest{} }
func (m *RemoveEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveEndpointRequest) ProtoMessage()    {}
func (*RemoveEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{11}
}

func (m *RemoveEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEndpointRequest.Unmarshal(m, b)
}
func (m *RemoveEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEndpointRequest.Marshal(b, m, deterministic)
}
func (m *RemoveEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEndpointRequest.Merge(m, src)
}
func (m *RemoveEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveEndpointRequest.Size(m)
}
func (m *RemoveEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEndpointRequest proto.InternalMessageInfo

func (m *RemoveEndpointRequest) GetEndpointId() string {
	if m != nil {
		return m.EndpointId
	}
	return ""
}

type GetEndpointRequest struct {
	EndpointId           string   `protobuf:"bytes,1,opt,name=endpointId,proto3" json:"endpointId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEndpointRequest) Reset()         { *m = GetEndpointRequest{} }
func (m *GetEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetEndpointRequest) ProtoMessage()    {}
func (*GetEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{12}
}

func (m *GetEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEndpointRequest.Unmarshal(m, b)
}
func (m *GetEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEndpointRequest.Merge(m, src)
}
func (m *GetEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetEndpointRequest.Size(m)
}
func (m *GetEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEndpointRequest proto.InternalMessageInfo

func (m *GetEndpointRequest) GetEndpointId() string {
	if m != nil {
		return m.EndpointId
	}
	return ""
}

type GetEndpointResponse struct {
	Endpoint             *Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetEndpointResponse) Reset()         { *m = GetEndpointResponse{} }
func (m *GetEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*GetEndpointResponse) ProtoMessage()    {}
func (*GetEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{13}
}

func (m *GetEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEndpointResponse.Unmarshal(m, b)
}
func (m *GetEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEndpointResponse.Marshal(b, m, deterministic)
}
func (m *GetEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEndpointResponse.Merge(m, src)
}
func (m *GetEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_GetEndpointResponse.Size(m)
}
func (m *GetEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEndpointResponse proto.InternalMessageInfo

func (m *GetEndpointResponse) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type Router struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fingerprint          string   `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	ListenerAddress      string   `protobuf:"bytes,3,opt,name=listenerAddress,proto3" json:"listenerAddress,omitempty"`
	Connected            bool     `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Router) Reset()         { *m = Router{} }
func (m *Router) String() string { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()    {}
func (*Router) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{14}
}

func (m *Router) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Router.Unmarshal(m, b)
}
func (m *Router) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Router.Marshal(b, m, deterministic)
}
func (m *Router) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Router.Merge(m, src)
}
func (m *Router) XXX_Size() int {
	return xxx_messageInfo_Router.Size(m)
}
func (m *Router) XXX_DiscardUnknown() {
	xxx_messageInfo_Router.DiscardUnknown(m)
}

var xxx_messageInfo_Router proto.InternalMessageInfo

func (m *Router) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Router) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *Router) GetListenerAddress() string {
	if m != nil {
		return m.ListenerAddress
	}
	return ""
}

func (m *Router) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

type ListRoutersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoutersRequest) Reset()         { *m = ListRoutersRequest{} }
func (m *ListRoutersRequest) String() string { return proto.CompactTextString(m) }
func (*ListRoutersRequest) ProtoMessage()    {}
func (*ListRoutersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{15}
}

func (m *ListRoutersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoutersRequest.Unmarshal(m, b)
}
func (m *ListRoutersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoutersRequest.Marshal(b, m, deterministic)
}
func (m *ListRoutersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoutersRequest.Merge(m, src)
}
func (m *ListRoutersRequest) XXX_Size() int {
	return xxx_messageInfo_ListRoutersRequest.Size(m)
}
func (m *ListRoutersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoutersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoutersRequest proto.InternalMessageInfo

type ListRoutersResponse struct {
	Routers              []*Router `protobuf:"bytes,1,rep,name=routers,proto3" json:"routers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRoutersResponse) Reset()         { *m = ListRoutersResponse{} }
func (m *ListRoutersResponse) String() string { return proto.CompactTextString(m) }
func (*ListRoutersResponse) ProtoMessage()    {}
func (*ListRoutersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{16}
}

func (m *ListRoutersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoutersResponse.Unmarshal(m, b)
}
func (m *ListRoutersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoutersResponse.Marshal(b, m, deterministic)
}
func (m *ListRoutersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoutersResponse.Merge(m, src)
}
func (m *ListRoutersResponse) XXX_Size() int {
	return xxx_messageInfo_ListRoutersResponse.Size(m)
}
func (m *ListRoutersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoutersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoutersResponse proto.InternalMessageInfo

func (m *ListRoutersResponse) GetRouters() []*Router {
	if m != nil {
		return m.Routers
	}
	return nil
}

type CreateRouterRequest struct {
	Router               *Router  `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRouterRequest) Reset()         { *m = CreateRouterRequest{} }
func (m *CreateRouterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRouterRequest) ProtoMessage()    {}
func (*CreateRouterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{17}
}

func (m *CreateRouterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRouterRequest.Unmarshal(m, b)
}
func (m *CreateRouterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRouterRequest.Marshal(b, m, deterministic)
}
func (m *CreateRouterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRouterRequest.Merge(m, src)
}
func (m *CreateRouterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRouterRequest.Size(m)
}
func (m *CreateRouterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRouterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRouterRequest proto.InternalMessageInfo

func (m *CreateRouterRequest) GetRouter() *Router {
	if m != nil {
		return m.Router
	}
	return nil
}

type RemoveRouterRequest struct {
	RouterId             string   `protobuf:"bytes,1,opt,name=routerId,proto3" json:"routerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRouterRequest) Reset()         { *m = RemoveRouterRequest{} }
func (m *RemoveRouterRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRouterRequest) ProtoMessage()    {}
func (*RemoveRouterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{18}
}

func (m *RemoveRouterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRouterRequest.Unmarshal(m, b)
}
func (m *RemoveRouterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRouterRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRouterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRouterRequest.Merge(m, src)
}
func (m *RemoveRouterRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRouterRequest.Size(m)
}
func (m *RemoveRouterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRouterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRouterRequest proto.InternalMessageInfo

func (m *RemoveRouterRequest) GetRouterId() string {
	if m != nil {
		return m.RouterId
	}
	return ""
}

type Link struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Src                  string   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  string   `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Down                 bool     `protobuf:"varint,5,opt,name=down,proto3" json:"down,omitempty"`
	Cost                 int32    `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	SrcLatency           int64    `protobuf:"varint,7,opt,name=srcLatency,proto3" json:"srcLatency,omitempty"`
	DstLatency           int64    `protobuf:"varint,8,opt,name=dstLatency,proto3" json:"dstLatency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{19}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Link) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Link) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *Link) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Link) GetDown() bool {
	if m != nil {
		return m.Down
	}
	return false
}

func (m *Link) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Link) GetSrcLatency() int64 {
	if m != nil {
		return m.SrcLatency
	}
	return 0
}

func (m *Link) GetDstLatency() int64 {
	if m != nil {
		return m.DstLatency
	}
	return 0
}

type ListLinksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLinksRequest) Reset()         { *m = ListLinksRequest{} }
func (m *ListLinksRequest) String() string { return proto.CompactTextString(m) }
func (*ListLinksRequest) ProtoMessage()    {}
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{20}
}

func (m *ListLinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLinksRequest.Unmarshal(m, b)
}
func (m *ListLinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLinksRequest.Marshal(b, m, deterministic)
}
func (m *ListLinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLinksRequest.Merge(m, src)
}
func (m *ListLinksRequest) XXX_Size() int {
	return xxx_messageInfo_ListLinksRequest.Size(m)
}
func (m *ListLinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLinksRequest proto.InternalMessageInfo

type ListLinksResponse struct {
	Links                []*Link  `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLinksResponse) Reset()         { *m = ListLinksResponse{} }
func (m *ListLinksResponse) String() string { return proto.CompactTextString(m) }
func (*ListLinksResponse) ProtoMessage()    {}
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{21}
}

func (m *ListLinksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLinksResponse.Unmarshal(m, b)
}
func (m *ListLinksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLinksResponse.Marshal(b, m, deterministic)
}
func (m *ListLinksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLinksResponse.Merge(m, src)
}
func (m *ListLinksResponse) XXX_Size() int {
	return xxx_messageInfo_ListLinksResponse.Size(m)
}
func (m *ListLinksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLinksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLinksResponse proto.InternalMessageInfo

func (m *ListLinksResponse) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

type SetLinkCostRequest struct {
	LinkId               string   `protobuf:"bytes,1,opt,name=linkId,proto3" json:"linkId,omitempty"`
	Cost                 int32    `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLinkCostRequest) Reset()         { *m = SetLinkCostRequest{} }
func (m *SetLinkCostRequest) String() string { return proto.CompactTextString(m) }
func (*SetLinkCostRequest) ProtoMessage()    {}
func (*SetLinkCostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{22}
}

func (m *SetLinkCostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLinkCostRequest.Unmarshal(m, b)
}
func (m *SetLinkCostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLinkCostRequest.Marshal(b, m, deterministic)
}
func (m *SetLinkCostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLinkCostRequest.Merge(m, src)
}
func (m *SetLinkCostRequest) XXX_Size() int {
	return xxx_messageInfo_SetLinkCostRequest.Size(m)
}
func (m *SetLinkCostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLinkCostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLinkCostRequest proto.InternalMessageInfo

func (m *SetLinkCostRequest) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *SetLinkCostRequest) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type SetLinkDownRequest struct {
	LinkId               string   `protobuf:"bytes,1,opt,name=linkId,proto3" json:"linkId,omitempty"`
	Down                 bool     `protobuf:"varint,2,opt,name=down,proto3" json:"down,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLinkDownRequest) Reset()         { *m = SetLinkDownRequest{} }
func (m *SetLinkDownRequest) String() string { return proto.CompactTextString(m) }
func (*SetLinkDownRequest) ProtoMessage()    {}
func (*SetLinkDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{23}
}

func (m *SetLinkDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLinkDownRequest.Unmarshal(m, b)
}
func (m *SetLinkDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLinkDownRequest.Marshal(b, m, deterministic)
}
func (m *SetLinkDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLinkDownRequest.Merge(m, src)
}
func (m *SetLinkDownRequest) XXX_Size() int {
	return xxx_messageInfo_SetLinkDownRequest.Size(m)
}
func (m *SetLinkDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLinkDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLinkDownRequest proto.InternalMessageInfo

func (m *SetLinkDownRequest) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *SetLinkDownRequest) GetDown() bool {
	if m != nil {
		return m.Down
	}
	return false
}

type Circuit struct {
	Path                 []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Links                []string `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Circuit) Reset()         { *m = Circuit{} }
func (m *Circuit) String() string { return proto.CompactTextString(m) }
func (*Circuit) ProtoMessage()    {}
func (*Circuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{24}
}

func (m *Circuit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circuit.Unmarshal(m, b)
}
func (m *Circuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circuit.Marshal(b, m, deterministic)
}
func (m *Circuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circuit.Merge(m, src)
}
func (m *Circuit) XXX_Size() int {
	return xxx_messageInfo_Circuit.Size(m)
}
func (m *Circuit) XXX_DiscardUnknown() {
	xxx_messageInfo_Circuit.DiscardUnknown(m)
}

var xxx_messageInfo_Circuit proto.InternalMessageInfo

func (m *Circuit) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Circuit) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

type Session struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ServiceId            string   `protobuf:"bytes,3,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	EndpointId           string   `protobuf:"bytes,4,opt,name=endpointId,proto3" json:"endpointId,omitempty"`
	Circuit              *Circuit `protobuf:"bytes,5,opt,name=circuit,proto3" json:"circuit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{25}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Session) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Session) GetEndpointId() string {
	if m != nil {
		return m.EndpointId
	}
	return ""
}

func (m *Session) GetCircuit() *Circuit {
	if m != nil {
		return m.Circuit
	}
	return nil
}

type ListSessionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSessionsRequest) Reset()         { *m = ListSessionsRequest{} }
func (m *ListSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSessionsRequest) ProtoMessage()    {}
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{26}
}

func (m *ListSessionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionsRequest.Unmarshal(m, b)
}
func (m *ListSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionsRequest.Marshal(b, m, deterministic)
}
func (m *ListSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionsRequest.Merge(m, src)
}
func (m *ListSessionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSessionsRequest.Size(m)
}
func (m *ListSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionsRequest proto.InternalMessageInfo

type ListSessionsResponse struct {
	Sessions             []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListSessionsResponse) Reset()         { *m = ListSessionsResponse{} }
func (m *ListSessionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSessionsResponse) ProtoMessage()    {}
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{27}
}

func (m *ListSessionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionsResponse.Unmarshal(m, b)
}
func (m *ListSessionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionsResponse.Marshal(b, m, deterministic)
}
func (m *ListSessionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionsResponse.Merge(m, src)
}
func (m *ListSessionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSessionsResponse.Size(m)
}
func (m *ListSessionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionsResponse proto.InternalMessageInfo

func (m *ListSessionsResponse) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type RemoveSessionRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Now                  bool     `protobuf:"varint,2,opt,name=now,proto3" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSessionRequest) Reset()         { *m = RemoveSessionRequest{} }
func (m *RemoveSessionRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveSessionRequest) ProtoMessage()    {}
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{28}
}

func (m *RemoveSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSessionRequest.Unmarshal(m, b)
}
func (m *RemoveSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSessionRequest.Marshal(b, m, deterministic)
}
func (m *RemoveSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSessionRequest.Merge(m, src)
}
func (m *RemoveSessionRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveSessionRequest.Size(m)
}
func (m *RemoveSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSessionRequest proto.InternalMessageInfo

func (m *RemoveSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *RemoveSessionRequest) GetNow() bool {
	if m != nil {
		return m.Now
	}
	return false
}

type StreamMetricsRequest struct {
	Matchers             []*StreamMetricsRequest_MetricMatcher `protobuf:"bytes,1,rep,name=matchers,proto3" json:"matchers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *StreamMetricsRequest) Reset()         { *m = StreamMetricsRequest{} }
func (m *StreamMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamMetricsRequest) ProtoMessage()    {}
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{29}
}

func (m *StreamMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetricsRequest.Unmarshal(m, b)
}
func (m *StreamMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetricsRequest.Marshal(b, m, deterministic)
}
func (m *StreamMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetricsRequest.Merge(m, src)
}
func (m *StreamMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamMetricsRequest.Size(m)
}
func (m *StreamMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetricsRequest proto.InternalMessageInfo

func (m *StreamMetricsRequest) GetMatchers() []*StreamMetricsRequest_MetricMatcher {
	if m != nil {
		return m.Matchers
	}
	return nil
}

type StreamMetricsRequest_MetricMatcher struct {
	NameRegex            string   `protobuf:"bytes,1,opt,name=nameRegex,proto3" json:"nameRegex,omitempty"`
	SourceIDRegex        string   `protobuf:"bytes,2,opt,name=sourceIDRegex,proto3" json:"sourceIDRegex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMetricsRequest_MetricMatcher) Reset()         { *m = StreamMetricsRequest_MetricMatcher{} }
func (m *StreamMetricsRequest_MetricMatcher) String() string { return proto.CompactTextString(m) }
func (*StreamMetricsRequest_MetricMatcher) ProtoMessage()    {}
func (*StreamMetricsRequest_MetricMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{29, 0}
}

func (m *StreamMetricsRequest_MetricMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetricsRequest_MetricMatcher.Unmarshal(m, b)
}
func (m *StreamMetricsRequest_MetricMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetricsRequest_MetricMatcher.Marshal(b, m, deterministic)
}
func (m *StreamMetricsRequest_MetricMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetricsRequest_MetricMatcher.Merge(m, src)
}
func (m *StreamMetricsRequest_MetricMatcher) XXX_Size() int {
	return xxx_messageInfo_StreamMetricsRequest_MetricMatcher.Size(m)
}
func (m *StreamMetricsRequest_MetricMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetricsRequest_MetricMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetricsRequest_MetricMatcher proto.InternalMessageInfo

func (m *StreamMetricsRequest_MetricMatcher) GetNameRegex() string {
	if m != nil {
		return m.NameRegex
	}
	return ""
}

func (m *StreamMetricsRequest_MetricMatcher) GetSourceIDRegex() string {
	if m != nil {
		return m.SourceIDRegex
	}
	return ""
}

type StreamMetricsEvent struct {
	SourceId             string                               `protobuf:"bytes,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	Timestamp            *timestamp.Timestamp                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags                 map[string]string                    `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IntMetrics           map[string]int64                     `protobuf:"bytes,4,rep,name=intMetrics,proto3" json:"intMetrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	FloatMetrics         map[string]float64                   `protobuf:"bytes,5,rep,name=floatMetrics,proto3" json:"floatMetrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	IntervalMetrics      []*StreamMetricsEvent_IntervalMetric `protobuf:"bytes,6,rep,name=intervalMetrics,proto3" json:"intervalMetrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *StreamMetricsEvent) Reset()         { *m = StreamMetricsEvent{} }
func (m *StreamMetricsEvent) String() string { return proto.CompactTextString(m) }
func (*StreamMetricsEvent) ProtoMessage()    {}
func (*StreamMetricsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{30}
}

func (m *StreamMetricsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetricsEvent.Unmarshal(m, b)
}
func (m *StreamMetricsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetricsEvent.Marshal(b, m, deterministic)
}
func (m *StreamMetricsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetricsEvent.Merge(m, src)
}
func (m *StreamMetricsEvent) XXX_Size() int {
	return xxx_messageInfo_StreamMetricsEvent.Size(m)
}
func (m *StreamMetricsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetricsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetricsEvent proto.InternalMessageInfo

func (m *StreamMetricsEvent) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *StreamMetricsEvent) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *StreamMetricsEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StreamMetricsEvent) GetIntMetrics() map[string]int64 {
	if m != nil {
		return m.IntMetrics
	}
	return nil
}

func (m *StreamMetricsEvent) GetFloatMetrics() map[string]float64 {
	if m != nil {
		return m.FloatMetrics
	}
	return nil
}

func (m *StreamMetricsEvent) GetIntervalMetrics() []*StreamMetricsEvent_IntervalMetric {
	if m != nil {
		return m.IntervalMetrics
	}
	return nil
}

type StreamMetricsEvent_IntervalMetric struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IntervalStartUTC     *timestamp.Timestamp `protobuf:"bytes,2,opt,name=intervalStartUTC,proto3" json:"intervalStartUTC,omitempty"`
	IntervalEndUTC       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=intervalEndUTC,proto3" json:"intervalEndUTC,omitempty"`
	Values               map[string]uint64    `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StreamMetricsEvent_IntervalMetric) Reset()         { *m = StreamMetricsEvent_IntervalMetric{} }
func (m *StreamMetricsEvent_IntervalMetric) String() string { return proto.CompactTextString(m) }
func (*StreamMetricsEvent_IntervalMetric) ProtoMessage()    {}
func (*StreamMetricsEvent_IntervalMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{30, 3}
}

func (m *StreamMetricsEvent_IntervalMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetricsEvent_IntervalMetric.Unmarshal(m, b)
}
func (m *StreamMetricsEvent_IntervalMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetricsEvent_IntervalMetric.Marshal(b, m, deterministic)
}
func (m *StreamMetricsEvent_IntervalMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetricsEvent_IntervalMetric.Merge(m, src)
}
func (m *StreamMetricsEvent_IntervalMetric) XXX_Size() int {
	return xxx_messageInfo_StreamMetricsEvent_IntervalMetric.Size(m)
}
func (m *StreamMetricsEvent_IntervalMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetricsEvent_IntervalMetric.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetricsEvent_IntervalMetric proto.InternalMessageInfo

func (m *StreamMetricsEvent_IntervalMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamMetricsEvent_IntervalMetric) GetIntervalStartUTC() *timestamp.Timestamp {
	if m != nil {
		return m.IntervalStartUTC
	}
	return nil
}

func (m *StreamMetricsEvent_IntervalMetric) GetIntervalEndUTC() *timestamp.Timestamp {
	if m != nil {
		return m.IntervalEndUTC
	}
	return nil
}

func (m *StreamMetricsEvent_IntervalMetric) GetValues() map[string]uint64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type StreamSessionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamSessionsRequest) Reset()         { *m = StreamSessionsRequest{} }
func (m *StreamSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamSessionsRequest) ProtoMessage()    {}
func (*StreamSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{31}
}

func (m *StreamSessionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSessionsRequest.Unmarshal(m, b)
}
func (m *StreamSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSessionsRequest.Marshal(b, m, deterministic)
}
func (m *StreamSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSessionsRequest.Merge(m, src)
}
func (m *StreamSessionsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamSessionsRequest.Size(m)
}
func (m *StreamSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSessionsRequest proto.InternalMessageInfo

type StreamSessionsEvent struct {
	EventType            StreamSessionEventType `protobuf:"varint,1,opt,name=eventType,proto3,enum=mgmt_pb.StreamSessionEventType" json:"eventType,omitempty"`
	SessionId            string                 `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ClientId             string                 `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ServiceId            string                 `protobuf:"bytes,4,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Circuit              *Circuit               `protobuf:"bytes,5,opt,name=circuit,proto3" json:"circuit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StreamSessionsEvent) Reset()         { *m = StreamSessionsEvent{} }
func (m *StreamSessionsEvent) String() string { return proto.CompactTextString(m) }
func (*StreamSessionsEvent) ProtoMessage()    {}
func (*StreamSessionsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{32}
}

func (m *StreamSessionsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSessionsEvent.Unmarshal(m, b)
}
func (m *StreamSessionsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSessionsEvent.Marshal(b, m, deterministic)
}
func (m *StreamSessionsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSessionsEvent.Merge(m, src)
}
func (m *StreamSessionsEvent) XXX_Size() int {
	return xxx_messageInfo_StreamSessionsEvent.Size(m)
}
func (m *StreamSessionsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSessionsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSessionsEvent proto.InternalMessageInfo

func (m *StreamSessionsEvent) GetEventType() StreamSessionEventType {
	if m != nil {
		return m.EventType
	}
	return StreamSessionEventType_SessionCreated
}

func (m *StreamSessionsEvent) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *StreamSessionsEvent) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *StreamSessionsEvent) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *StreamSessionsEvent) GetCircuit() *Circuit {
	if m != nil {
		return m.Circuit
	}
	return nil
}

type ToggleSessionTracesRequest struct {
	Enable               bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	ServiceRegex         string   `protobuf:"bytes,2,opt,name=serviceRegex,proto3" json:"serviceRegex,omitempty"`
	ClientRegex          string   `protobuf:"bytes,3,opt,name=clientRegex,proto3" json:"clientRegex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleSessionTracesRequest) Reset()         { *m = ToggleSessionTracesRequest{} }
func (m *ToggleSessionTracesRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleSessionTracesRequest) ProtoMessage()    {}
func (*ToggleSessionTracesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{33}
}

func (m *ToggleSessionTracesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleSessionTracesRequest.Unmarshal(m, b)
}
func (m *ToggleSessionTracesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleSessionTracesRequest.Marshal(b, m, deterministic)
}
func (m *ToggleSessionTracesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleSessionTracesRequest.Merge(m, src)
}
func (m *ToggleSessionTracesRequest) XXX_Size() int {
	return xxx_messageInfo_ToggleSessionTracesRequest.Size(m)
}
func (m *ToggleSessionTracesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleSessionTracesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleSessionTracesRequest proto.InternalMessageInfo

func (m *ToggleSessionTracesRequest) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *ToggleSessionTracesRequest) GetServiceRegex() string {
	if m != nil {
		return m.ServiceRegex
	}
	return ""
}

func (m *ToggleSessionTracesRequest) GetClientRegex() string {
	if m != nil {
		return m.ClientRegex
	}
	return ""
}

type StreamTracesRequest struct {
	EnabledFilter        bool            `protobuf:"varint,1,opt,name=enabledFilter,proto3" json:"enabledFilter,omitempty"`
	FilterType           TraceFilterType `protobuf:"varint,2,opt,name=filterType,proto3,enum=mgmt_pb.TraceFilterType" json:"filterType,omitempty"`
	ContentTypes         []int32         `protobuf:"varint,3,rep,packed,name=contentTypes,proto3" json:"contentTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StreamTracesRequest) Reset()         { *m = StreamTracesRequest{} }
func (m *StreamTracesRequest) String() string { return proto.CompactTextString(m) }
func (*StreamTracesRequest) ProtoMessage()    {}
func (*StreamTracesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{34}
}

func (m *StreamTracesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTracesRequest.Unmarshal(m, b)
}
func (m *StreamTracesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTracesRequest.Marshal(b, m, deterministic)
}
func (m *StreamTracesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTracesRequest.Merge(m, src)
}
func (m *StreamTracesRequest) XXX_Size() int {
	return xxx_messageInfo_StreamTracesRequest.Size(m)
}
func (m *StreamTracesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTracesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTracesRequest proto.InternalMessageInfo

func (m *StreamTracesRequest) GetEnabledFilter() bool {
	if m != nil {
		return m.EnabledFilter
	}
	return false
}

func (m *StreamTracesRequest) GetFilterType() TraceFilterType {
	if m != nil {
		return m.FilterType
	}
	return TraceFilterType_EXCLUDE
}

func (m *StreamTracesRequest) GetContentTypes() []int32 {
	if m != nil {
		return m.ContentTypes
	}
	return nil
}

type InspectRequest struct {
	AppRegex             string   `protobuf:"bytes,1,opt,name=appRegex,proto3" json:"appRegex,omitempty"`
	RequestedValues      []string `protobuf:"bytes,2,rep,name=requestedValues,proto3" json:"requestedValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InspectRequest) Reset()         { *m = InspectRequest{} }
func (m *InspectRequest) String() string { return proto.CompactTextString(m) }
func (*InspectRequest) ProtoMessage()    {}
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{35}
}

func (m *InspectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectRequest.Unmarshal(m, b)
}
func (m *InspectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectRequest.Marshal(b, m, deterministic)
}
func (m *InspectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectRequest.Merge(m, src)
}
func (m *InspectRequest) XXX_Size() int {
	return xxx_messageInfo_InspectRequest.Size(m)
}
func (m *InspectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InspectRequest proto.InternalMessageInfo

func (m *InspectRequest) GetAppRegex() string {
	if m != nil {
		return m.AppRegex
	}
	return ""
}

func (m *InspectRequest) GetRequestedValues() []string {
	if m != nil {
		return m.RequestedValues
	}
	return nil
}

type InspectResponse struct {
	Success              bool                            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Errors               []string                        `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Values               []*InspectResponse_InspectValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *InspectResponse) Reset()         { *m = InspectResponse{} }
func (m *InspectResponse) String() string { return proto.CompactTextString(m) }
func (*InspectResponse) ProtoMessage()    {}
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{36}
}

func (m *InspectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectResponse.Unmarshal(m, b)
}
func (m *InspectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectResponse.Marshal(b, m, deterministic)
}
func (m *InspectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectResponse.Merge(m, src)
}
func (m *InspectResponse) XXX_Size() int {
	return xxx_messageInfo_InspectResponse.Size(m)
}
func (m *InspectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InspectResponse proto.InternalMessageInfo

func (m *InspectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *InspectResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *InspectResponse) GetValues() []*InspectResponse_InspectValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type InspectResponse_InspectValue struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InspectResponse_InspectValue) Reset()         { *m = InspectResponse_InspectValue{} }
func (m *InspectResponse_InspectValue) String() string { return proto.CompactTextString(m) }
func (*InspectResponse_InspectValue) ProtoMessage()    {}
func (*InspectResponse_InspectValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{36, 0}
}

func (m *InspectResponse_InspectValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectResponse_InspectValue.Unmarshal(m, b)
}
func (m *InspectResponse_InspectValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectResponse_InspectValue.Marshal(b, m, deterministic)
}
func (m *InspectResponse_InspectValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectResponse_InspectValue.Merge(m, src)
}
func (m *InspectResponse_InspectValue) XXX_Size() int {
	return xxx_messageInfo_InspectResponse_InspectValue.Size(m)
}
func (m *InspectResponse_InspectValue) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectResponse_InspectValue.DiscardUnknown(m)
}

var xxx_messageInfo_InspectResponse_InspectValue proto.InternalMessageInfo

func (m *InspectResponse_InspectValue) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *InspectResponse_InspectValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InspectResponse_InspectValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("mgmt_pb.ContentType", ContentType_name, ContentType_value)
	proto.RegisterEnum("mgmt_pb.StreamSessionEventType", StreamSessionEventType_name, StreamSessionEventType_value)
	proto.RegisterEnum("mgmt_pb.TraceFilterType", TraceFilterType_name, TraceFilterType_value)
	proto.RegisterType((*Service)(nil), "mgmt_pb.Service")
	proto.RegisterType((*Endpoint)(nil), "mgmt_pb.Endpoint")
	proto.RegisterMapType((map[uint32][]byte)(nil), "mgmt_pb.Endpoint.PeerDataEntry")
	proto.RegisterType((*ListServicesRequest)(nil), "mgmt_pb.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "mgmt_pb.ListServicesResponse")
	proto.RegisterType((*CreateServiceRequest)(nil), "mgmt_pb.CreateServiceRequest")
	proto.RegisterType((*RemoveServiceRequest)(nil), "mgmt_pb.RemoveServiceRequest")
	proto.RegisterType((*GetServiceRequest)(nil), "mgmt_pb.GetServiceRequest")
	proto.RegisterType((*GetServiceResponse)(nil), "mgmt_pb.GetServiceResponse")
	proto.RegisterType((*ListEndpointsRequest)(nil), "mgmt_pb.ListEndpointsRequest")
	proto.RegisterType((*ListEndpointsResponse)(nil), "mgmt_pb.ListEndpointsResponse")
	proto.RegisterType((*CreateEndpointRequest)(nil), "mgmt_pb.CreateEndpointRequest")
	proto.RegisterType((*RemoveEndpointRequest)(nil), "mgmt_pb.RemoveEndpointRequest")
	proto.RegisterType((*GetEndpointRequest)(nil), "mgmt_pb.GetEndpointRequest")
	proto.RegisterType((*GetEndpointResponse)(nil), "mgmt_pb.GetEndpointResponse")
	proto.RegisterType((*Router)(nil), "mgmt_pb.Router")
	proto.RegisterType((*ListRoutersRequest)(nil), "mgmt_pb.ListRoutersRequest")
	proto.RegisterType((*ListRoutersResponse)(nil), "mgmt_pb.ListRoutersResponse")
	proto.RegisterType((*CreateRouterRequest)(nil), "mgmt_pb.CreateRouterRequest")
	proto.RegisterType((*RemoveRouterRequest)(nil), "mgmt_pb.RemoveRouterRequest")
	proto.RegisterType((*Link)(nil), "mgmt_pb.Link")
	proto.RegisterType((*ListLinksRequest)(nil), "mgmt_pb.ListLinksRequest")
	proto.RegisterType((*ListLinksResponse)(nil), "mgmt_pb.ListLinksResponse")
	proto.RegisterType((*SetLinkCostRequest)(nil), "mgmt_pb.SetLinkCostRequest")
	proto.RegisterType((*SetLinkDownRequest)(nil), "mgmt_pb.SetLinkDownRequest")
	proto.RegisterType((*Circuit)(nil), "mgmt_pb.Circuit")
	proto.RegisterType((*Session)(nil), "mgmt_pb.Session")
	proto.RegisterType((*ListSessionsRequest)(nil), "mgmt_pb.ListSessionsRequest")
	proto.RegisterType((*ListSessionsResponse)(nil), "mgmt_pb.ListSessionsResponse")
	proto.RegisterType((*RemoveSessionRequest)(nil), "mgmt_pb.RemoveSessionRequest")
	proto.RegisterType((*StreamMetricsRequest)(nil), "mgmt_pb.StreamMetricsRequest")
	proto.RegisterType((*StreamMetricsRequest_MetricMatcher)(nil), "mgmt_pb.StreamMetricsRequest.MetricMatcher")
	proto.RegisterType((*StreamMetricsEvent)(nil), "mgmt_pb.StreamMetricsEvent")
	proto.RegisterMapType((map[string]float64)(nil), "mgmt_pb.StreamMetricsEvent.FloatMetricsEntry")
	proto.RegisterMapType((map[string]int64)(nil), "mgmt_pb.StreamMetricsEvent.IntMetricsEntry")
	proto.RegisterMapType((map[string]string)(nil), "mgmt_pb.StreamMetricsEvent.TagsEntry")
	proto.RegisterType((*StreamMetricsEvent_IntervalMetric)(nil), "mgmt_pb.StreamMetricsEvent.IntervalMetric")
	proto.RegisterMapType((map[string]uint64)(nil), "mgmt_pb.StreamMetricsEvent.IntervalMetric.ValuesEntry")
	proto.RegisterType((*StreamSessionsRequest)(nil), "mgmt_pb.StreamSessionsRequest")
	proto.RegisterType((*StreamSessionsEvent)(nil), "mgmt_pb.StreamSessionsEvent")
	proto.RegisterType((*ToggleSessionTracesRequest)(nil), "mgmt_pb.ToggleSessionTracesRequest")
	proto.RegisterType((*StreamTracesRequest)(nil), "mgmt_pb.StreamTracesRequest")
	proto.RegisterType((*InspectRequest)(nil), "mgmt_pb.InspectRequest")
	proto.RegisterType((*InspectResponse)(nil), "mgmt_pb.InspectResponse")
	proto.RegisterType((*InspectResponse_InspectValue)(nil), "mgmt_pb.InspectResponse.InspectValue")
}

func init() { proto.RegisterFile("mgmt.proto", fileDescriptor_24cf82780fd24e73) }

var fileDescriptor_24cf82780fd24e73 = []byte{
	// 1786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x57, 0x49, 0x73, 0x1b, 0xc7,
	0x15, 0xce, 0x00, 0x20, 0x01, 0x3c, 0x6e, 0x60, 0x93, 0x94, 0x20, 0x28, 0x91, 0x54, 0x93, 0xa4,
	0xc2, 0x50, 0x11, 0x54, 0x91, 0x52, 0x91, 0x14, 0x95, 0x12, 0x49, 0x5c, 0x14, 0x55, 0xa8, 0x29,
	0x66, 0x48, 0xa9, 0x52, 0xb9, 0xa4, 0x86, 0x40, 0x13, 0x42, 0x09, 0x98, 0x41, 0x66, 0x86, 0x54,
	0x98, 0xa3, 0xff, 0x81, 0xe5, 0xb2, 0x5d, 0xde, 0xca, 0x17, 0x2f, 0x37, 0xdb, 0x07, 0x1f, 0x64,
	0x4b, 0xde, 0xb7, 0xbb, 0x4f, 0xfe, 0x27, 0xbe, 0xba, 0xfb, 0xf5, 0x32, 0x3d, 0x8b, 0x45, 0xf2,
	0x36, 0xfd, 0xbe, 0xf7, 0xde, 0xbc, 0xa5, 0xfb, 0xeb, 0xd7, 0x00, 0xc3, 0xde, 0x30, 0x6e, 0x8f,
	0xc2, 0x20, 0x0e, 0x48, 0x95, 0x7f, 0xff, 0x67, 0xb4, 0xdd, 0x3a, 0xdd, 0x0b, 0x82, 0xde, 0x80,
	0x9e, 0x47, 0xf1, 0xf6, 0xee, 0xce, 0xf9, 0xb8, 0x3f, 0xa4, 0x51, 0xec, 0x0d, 0x47, 0x42, 0xd3,
	0xde, 0x83, 0xea, 0x26, 0x0d, 0xf7, 0xfa, 0x1d, 0x4a, 0xa6, 0xa1, 0xd4, 0xef, 0x36, 0xad, 0x33,
	0xd6, 0x62, 0xdd, 0x65, 0x5f, 0x64, 0x09, 0x1a, 0xd4, 0xef, 0x8e, 0x82, 0xbe, 0x1f, 0x6f, 0xc6,
	0xa1, 0x17, 0xd3, 0xde, 0x7e, 0xb3, 0x84, 0x68, 0x4e, 0x4e, 0xce, 0x43, 0x5d, 0xc9, 0xa2, 0x66,
	0xf9, 0x4c, 0x79, 0x71, 0xe2, 0xc2, 0x6c, 0x5b, 0x06, 0xd1, 0x5e, 0x95, 0x88, 0x9b, 0xe8, 0xd8,
	0x4f, 0x4b, 0x50, 0x53, 0xf2, 0xdc, 0x9f, 0x7f, 0x09, 0xf5, 0x48, 0x04, 0x75, 0xbb, 0x2b, 0x7f,
	0x99, 0x08, 0x48, 0x0b, 0x6a, 0x61, 0xb0, 0x1b, 0xd3, 0x90, 0x81, 0x65, 0x04, 0xf5, 0x9a, 0x34,
	0xa1, 0xba, 0xdd, 0xf7, 0xbb, 0x7d, 0xbf, 0xd7, 0xac, 0x20, 0xa4, 0x96, 0x1c, 0xf1, 0xba, 0xdd,
	0x90, 0x46, 0x51, 0x73, 0x4c, 0x20, 0x72, 0x49, 0x2e, 0x43, 0xbd, 0x13, 0x52, 0x96, 0x47, 0xf7,
	0x46, 0xdc, 0x1c, 0x67, 0xd8, 0xc4, 0x85, 0x56, 0x5b, 0xd4, 0xad, 0xad, 0xea, 0xd6, 0xde, 0x52,
	0x75, 0x73, 0x13, 0x65, 0x72, 0x15, 0x6a, 0x23, 0x4a, 0xc3, 0x15, 0x2f, 0xf6, 0x9a, 0x55, 0x4c,
	0xfa, 0x74, 0x2e, 0xe9, 0xf6, 0x86, 0xd4, 0x58, 0xf5, 0xe3, 0x70, 0xdf, 0xd5, 0x06, 0xad, 0xab,
	0x30, 0x95, 0x82, 0x48, 0x03, 0xca, 0x0f, 0xe8, 0x3e, 0x96, 0x61, 0xca, 0xe5, 0x9f, 0x64, 0x1e,
	0xc6, 0xf6, 0xbc, 0xc1, 0x2e, 0xc5, 0x1a, 0x4c, 0xba, 0x62, 0xf1, 0x97, 0xd2, 0x65, 0xcb, 0x5e,
	0x80, 0xb9, 0xf5, 0x7e, 0x14, 0xcb, 0xd6, 0x45, 0x2e, 0xfd, 0xef, 0x2e, 0x0b, 0xcf, 0x5e, 0x81,
	0xf9, 0xb4, 0x38, 0x1a, 0x05, 0x7e, 0x44, 0xc9, 0x1f, 0xa0, 0x26, 0xeb, 0x17, 0x31, 0xff, 0x3c,
	0xd0, 0x86, 0x0e, 0x54, 0x2a, 0xbb, 0x5a, 0xc3, 0xbe, 0x09, 0xf3, 0xcb, 0x98, 0xa3, 0x82, 0x84,
	0x77, 0xb6, 0x21, 0xaa, 0x52, 0x07, 0x83, 0x2c, 0x72, 0xa2, 0x14, 0xec, 0x3f, 0xc1, 0xbc, 0x4b,
	0x87, 0xc1, 0x5e, 0xd6, 0x47, 0xaa, 0xb5, 0x56, 0xa6, 0xb5, 0xf6, 0x1f, 0x61, 0xf6, 0x16, 0x8d,
	0x8f, 0x64, 0x72, 0x1d, 0x88, 0x69, 0x22, 0x13, 0x3e, 0x4a, 0xa8, 0x1b, 0xa2, 0x68, 0xaa, 0x61,
	0xd1, 0xa1, 0xfe, 0x9b, 0xda, 0x85, 0xa5, 0xf4, 0x2e, 0xb4, 0xff, 0x0e, 0x0b, 0x19, 0x8f, 0x32,
	0xac, 0xd4, 0x31, 0xb1, 0x0e, 0x71, 0x4c, 0xd6, 0x60, 0x41, 0xb4, 0x42, 0x83, 0x32, 0xb8, 0x73,
	0x50, 0x53, 0x5a, 0x32, 0xc3, 0x02, 0x47, 0x5a, 0xc5, 0xbe, 0x04, 0x0b, 0xa2, 0x1d, 0x59, 0x3f,
	0xa7, 0x00, 0x94, 0x92, 0xce, 0xd2, 0x90, 0xb0, 0x3e, 0xf2, 0xf2, 0x1e, 0xd5, 0x6a, 0x05, 0xe6,
	0x52, 0x56, 0x32, 0xfd, 0x23, 0x06, 0xfd, 0x9c, 0x05, 0xe3, 0x2e, 0xd6, 0x34, 0xc7, 0x10, 0x67,
	0x60, 0x62, 0x87, 0x9d, 0x6a, 0x1a, 0x8e, 0x42, 0xee, 0x4c, 0x34, 0xc0, 0x14, 0x91, 0x45, 0x98,
	0x19, 0xb0, 0x1e, 0x50, 0x9f, 0x86, 0x37, 0xe4, 0xb9, 0x17, 0x64, 0x91, 0x15, 0xf3, 0x3e, 0x77,
	0x02, 0xdf, 0xa7, 0x1d, 0x76, 0xa8, 0x91, 0x35, 0x6a, 0x6e, 0x22, 0xb0, 0xe7, 0x81, 0xf0, 0x5e,
	0x8a, 0x38, 0xf4, 0x41, 0xbb, 0x2e, 0xce, 0x9f, 0x96, 0xca, 0x04, 0x7f, 0x0f, 0x55, 0xb1, 0x09,
	0x54, 0x77, 0x67, 0x74, 0x7e, 0x42, 0xd5, 0x55, 0xb8, 0xfd, 0x57, 0x98, 0x13, 0x9d, 0x95, 0x80,
	0xac, 0xec, 0xef, 0x60, 0x5c, 0x68, 0xc8, 0x02, 0xe5, 0x1c, 0x48, 0x98, 0x1d, 0x95, 0x39, 0xd1,
	0xd1, 0xb4, 0xbd, 0xb9, 0x2d, 0xad, 0xcc, 0xb6, 0x7c, 0x6c, 0x41, 0x65, 0xbd, 0xef, 0x3f, 0xc8,
	0x55, 0x93, 0x31, 0x4f, 0x14, 0x76, 0x64, 0x15, 0xf9, 0x27, 0x97, 0x74, 0xa3, 0x58, 0x56, 0x8c,
	0x7f, 0x72, 0x2e, 0x62, 0xfc, 0x17, 0x53, 0xc9, 0xab, 0x62, 0x41, 0x08, 0x54, 0xba, 0xc1, 0x43,
	0x1f, 0x29, 0xb5, 0xe6, 0xe2, 0x37, 0x97, 0x75, 0x82, 0x48, 0x50, 0xe9, 0x98, 0x8b, 0xdf, 0x7c,
	0xc3, 0x30, 0xb7, 0xeb, 0xcc, 0xc4, 0xef, 0xec, 0x33, 0xae, 0xb4, 0x16, 0xcb, 0xae, 0x21, 0xe1,
	0x38, 0xfb, 0x89, 0xc2, 0x6b, 0x02, 0x4f, 0x24, 0x36, 0x81, 0x06, 0xaf, 0x37, 0x8f, 0x5e, 0xf7,
	0xe0, 0x32, 0xcc, 0x1a, 0x32, 0xd9, 0x81, 0x5f, 0xc3, 0xd8, 0x80, 0x0b, 0x64, 0xfd, 0xa7, 0x74,
	0xf9, 0xb8, 0x9a, 0x2b, 0x30, 0xce, 0x19, 0x9b, 0x14, 0x0d, 0x97, 0x59, 0x70, 0xaa, 0x74, 0xc7,
	0x60, 0x9c, 0xc3, 0xba, 0x70, 0x72, 0xa5, 0xf3, 0x29, 0x25, 0xf9, 0x18, 0x1e, 0x56, 0x58, 0xca,
	0x87, 0xf0, 0x80, 0x55, 0x2a, 0x25, 0x55, 0xb2, 0x2f, 0x42, 0x75, 0xb9, 0x1f, 0x76, 0x76, 0xfb,
	0x31, 0x87, 0x47, 0x5e, 0x7c, 0x1f, 0x43, 0xae, 0xbb, 0xf8, 0xcd, 0xcb, 0x2d, 0xf2, 0x28, 0xa1,
	0x50, 0x06, 0xfe, 0xa6, 0xc5, 0xaf, 0xeb, 0x28, 0xea, 0x07, 0x7e, 0xae, 0x89, 0xac, 0xf3, 0x9d,
	0x41, 0x9f, 0xe2, 0x89, 0x94, 0x84, 0xa4, 0xd6, 0x69, 0x2a, 0x2b, 0x67, 0xa9, 0x2c, 0x7d, 0x9a,
	0x2b, 0xd9, 0xd3, 0xcc, 0xc9, 0xb4, 0x23, 0x42, 0xc5, 0x3e, 0x9b, 0x64, 0x2a, 0x53, 0x70, 0x95,
	0x42, 0x72, 0x31, 0x61, 0x90, 0xf9, 0x8b, 0x49, 0x89, 0xcd, 0x8b, 0x49, 0xc8, 0x0a, 0x2e, 0x26,
	0x04, 0x5c, 0xad, 0xc1, 0xd8, 0x50, 0x5f, 0x2a, 0x02, 0x32, 0x99, 0x1a, 0x25, 0x26, 0x53, 0x4b,
	0x01, 0xdf, 0xcb, 0x7e, 0xf0, 0x50, 0x16, 0x9f, 0x7f, 0xda, 0x1f, 0x5a, 0x30, 0xcf, 0x46, 0x17,
	0xea, 0x0d, 0xef, 0xd0, 0x38, 0xec, 0x77, 0x34, 0xe5, 0xdf, 0x82, 0xda, 0xd0, 0x8b, 0x3b, 0xf7,
	0x93, 0x03, 0x7c, 0x36, 0x09, 0xa7, 0xc0, 0xa0, 0x2d, 0x96, 0x77, 0x84, 0x8d, 0xab, 0x8d, 0x5b,
	0x9b, 0x30, 0x95, 0x82, 0x78, 0x88, 0xbe, 0x37, 0x64, 0x17, 0x54, 0x8f, 0xfe, 0x4f, 0x85, 0xa8,
	0x05, 0xe4, 0x37, 0x30, 0x15, 0x05, 0xbb, 0x21, 0xeb, 0xc6, 0x8a, 0xd0, 0x10, 0x0d, 0x4c, 0x0b,
	0xed, 0x47, 0x55, 0xb6, 0xeb, 0xcc, 0x28, 0x56, 0xf7, 0x58, 0x7b, 0x79, 0xe3, 0xa5, 0x9e, 0x3e,
	0xf2, 0x6a, 0xcd, 0x67, 0x1b, 0x3d, 0xf1, 0xa1, 0xd3, 0x03, 0x66, 0x1b, 0xad, 0x4c, 0xae, 0x40,
	0x25, 0xf6, 0x7a, 0x6a, 0x98, 0xfb, 0x6d, 0x71, 0x19, 0x30, 0x80, 0xf6, 0x16, 0xd3, 0x13, 0xd3,
	0x0d, 0x9a, 0x90, 0x7f, 0x00, 0xb0, 0x8d, 0x23, 0x55, 0xd8, 0x7e, 0x7a, 0x46, 0x1d, 0x85, 0x83,
	0xdb, 0x5a, 0x5b, 0xb8, 0x31, 0xcc, 0xc9, 0x3f, 0x61, 0x72, 0x67, 0x10, 0x78, 0xda, 0xdd, 0x18,
	0xba, 0x3b, 0xf7, 0x2c, 0x77, 0x6b, 0x86, 0xbe, 0x70, 0x98, 0x72, 0x41, 0xb6, 0x60, 0x86, 0xfd,
	0x80, 0x6d, 0x7f, 0x6f, 0xa0, 0xbc, 0x8e, 0xa3, 0xd7, 0xa5, 0x03, 0x82, 0x34, 0x4c, 0xdc, 0xac,
	0x8b, 0xd6, 0x25, 0xa8, 0xeb, 0x42, 0x98, 0xb3, 0x5c, 0xbd, 0x60, 0x96, 0xab, 0x1b, 0xb3, 0x5c,
	0xeb, 0x1a, 0xcc, 0x64, 0x0a, 0x70, 0x90, 0x79, 0xd9, 0x34, 0xff, 0x1b, 0xcc, 0xe6, 0x12, 0x3e,
	0xc8, 0x81, 0x65, 0x3a, 0x78, 0x52, 0x82, 0xe9, 0x74, 0x72, 0x9c, 0x91, 0xf8, 0xe6, 0x94, 0xf6,
	0xf8, 0x4d, 0xd6, 0xa0, 0xa1, 0x52, 0xde, 0x8c, 0xbd, 0x30, 0xbe, 0xbb, 0xb5, 0x7c, 0x88, 0x1d,
	0x95, 0xb3, 0x21, 0x37, 0x61, 0x5a, 0xc9, 0xd8, 0x9d, 0xcf, 0xbd, 0x94, 0x0f, 0xf4, 0x92, 0xb1,
	0x20, 0x0e, 0x8c, 0x63, 0xfc, 0x6a, 0x77, 0xfd, 0xf9, 0xf0, 0x8d, 0x6b, 0xdf, 0x43, 0x43, 0xb1,
	0x2f, 0xa4, 0x97, 0xd6, 0x15, 0x98, 0x30, 0xc4, 0x07, 0x55, 0xaf, 0x62, 0x4e, 0xe2, 0xc7, 0x61,
	0x41, 0xfc, 0x33, 0x4b, 0x79, 0x3f, 0x58, 0x30, 0x97, 0x46, 0xc4, 0x71, 0xbd, 0xc6, 0x66, 0x40,
	0xfe, 0xb1, 0xb5, 0x3f, 0x12, 0x05, 0x9e, 0x36, 0x5e, 0x0d, 0x29, 0x83, 0x55, 0xa5, 0xe6, 0x26,
	0x16, 0x69, 0xae, 0x2b, 0x65, 0xb9, 0xce, 0xbc, 0x04, 0xca, 0xcf, 0xba, 0x04, 0x2a, 0xd9, 0x4b,
	0xe0, 0x28, 0x24, 0xff, 0x7f, 0x68, 0x6d, 0x05, 0x3d, 0xd6, 0x2b, 0x19, 0xe8, 0x56, 0xe8, 0x25,
	0x8f, 0x10, 0x7e, 0x0b, 0x52, 0xdf, 0xdb, 0x1e, 0x88, 0xec, 0x6a, 0xae, 0x5c, 0x11, 0x1b, 0x26,
	0x23, 0x35, 0xa6, 0x27, 0x1c, 0x97, 0x92, 0xf1, 0xb9, 0x4e, 0xc4, 0x2b, 0x54, 0x44, 0x0a, 0xa6,
	0xc8, 0x7e, 0x45, 0x97, 0x35, 0xfd, 0x57, 0x46, 0xa1, 0xe2, 0x3f, 0xdd, 0xb5, 0xfe, 0x40, 0xcd,
	0x4f, 0x35, 0x37, 0x2d, 0x64, 0x7c, 0x08, 0x3b, 0xf8, 0x85, 0xd5, 0x2f, 0x61, 0xf5, 0x9b, 0x3a,
	0x51, 0xf4, 0xb8, 0xa6, 0x71, 0xd7, 0xd0, 0xe5, 0xd1, 0xb3, 0xa1, 0x30, 0x96, 0x6d, 0x10, 0xbc,
	0x38, 0xe6, 0xa6, 0x64, 0xf6, 0x3d, 0x7e, 0x90, 0xa2, 0x11, 0x1b, 0x1c, 0x8d, 0x71, 0xcc, 0x1b,
	0x8d, 0x4c, 0xd6, 0xd7, 0x6b, 0x3e, 0xa1, 0x86, 0x42, 0x8d, 0x76, 0xc5, 0xee, 0x93, 0x97, 0x7d,
	0x56, 0x6c, 0x7f, 0x6f, 0x71, 0x8a, 0x90, 0x8e, 0xe5, 0xcd, 0xc9, 0xde, 0xb3, 0xd1, 0x6e, 0xa7,
	0xc3, 0xe7, 0x5a, 0x91, 0xa9, 0x5a, 0x62, 0xfd, 0xc3, 0x30, 0x08, 0x95, 0x3b, 0xb9, 0x62, 0x1b,
	0x4f, 0x1d, 0x9a, 0x2c, 0xa7, 0x67, 0x7c, 0xab, 0x35, 0xfe, 0x5d, 0x9f, 0x11, 0x07, 0x26, 0x4d,
	0x39, 0x3f, 0x12, 0x2c, 0x15, 0x7d, 0xe7, 0x88, 0x85, 0x66, 0x8e, 0x92, 0xc1, 0x1c, 0xfa, 0xf0,
	0x94, 0x0d, 0xea, 0x5b, 0xfa, 0xb1, 0x0a, 0x13, 0xcb, 0x49, 0xf5, 0x48, 0x0d, 0x2a, 0xff, 0xa6,
	0x61, 0xd0, 0xf8, 0x05, 0xdb, 0xa8, 0xc7, 0x0b, 0x1e, 0xb7, 0x5c, 0xa9, 0xf1, 0xbc, 0x43, 0x7e,
	0x05, 0xcd, 0xa2, 0x37, 0x2e, 0xc2, 0x8f, 0x10, 0x2e, 0x7a, 0xbc, 0x22, 0xfc, 0x02, 0xc2, 0x45,
	0xef, 0x52, 0x84, 0x5f, 0x74, 0x58, 0xbf, 0x16, 0x72, 0x0f, 0x50, 0xc4, 0x5e, 0x72, 0xc8, 0x49,
	0x38, 0x96, 0x7f, 0x69, 0x22, 0xf8, 0xb2, 0xc3, 0x66, 0xa8, 0x13, 0x85, 0x0f, 0x35, 0xc4, 0xbf,
	0x44, 0xbc, 0xf0, 0x01, 0x86, 0xf8, 0x57, 0x3a, 0xab, 0xec, 0x23, 0x14, 0xe1, 0xaf, 0xd1, 0xbc,
	0xf0, 0x45, 0x89, 0xf8, 0x37, 0x2a, 0xb6, 0x22, 0xdf, 0xdf, 0x3a, 0xbc, 0x9e, 0x05, 0xaf, 0x31,
	0x44, 0xbf, 0x43, 0xd3, 0xfc, 0x03, 0x07, 0xc1, 0x57, 0x1d, 0xd5, 0x8a, 0xcc, 0x3b, 0x07, 0xd1,
	0xd7, 0x10, 0x2d, 0x78, 0xc3, 0x20, 0xfa, 0x3a, 0xa2, 0x05, 0x2f, 0x14, 0x44, 0xdf, 0x70, 0xc8,
	0x09, 0x31, 0x11, 0x9a, 0x13, 0x3d, 0x42, 0x6f, 0x61, 0x13, 0x72, 0x83, 0x3d, 0x62, 0x6f, 0x63,
	0xb4, 0xf9, 0xd1, 0x1d, 0xc1, 0x77, 0x4c, 0xd0, 0x98, 0xca, 0x11, 0x7c, 0xd7, 0x49, 0x76, 0x55,
	0x8a, 0xa6, 0x11, 0x7d, 0xcf, 0xd8, 0x55, 0xe9, 0x01, 0x15, 0xe1, 0xf7, 0x53, 0xdb, 0xc6, 0x9c,
	0x3c, 0x11, 0xfe, 0x00, 0xe1, 0xa2, 0xf1, 0x10, 0xe1, 0xc7, 0x22, 0xae, 0xdc, 0xbd, 0x84, 0xe0,
	0x47, 0xd8, 0xda, 0xc2, 0x0b, 0x04, 0xf1, 0x8f, 0x31, 0xee, 0x82, 0x6b, 0x04, 0xd1, 0x27, 0x0e,
	0x23, 0xcc, 0x93, 0x82, 0x8a, 0x37, 0xfa, 0x23, 0x9a, 0x62, 0x44, 0xd4, 0x78, 0xea, 0xb0, 0x17,
	0xd1, 0xa9, 0x9f, 0x27, 0x6b, 0x54, 0xfa, 0xc4, 0xf8, 0x49, 0x1e, 0xfd, 0x14, 0x1b, 0x62, 0xa2,
	0x49, 0x00, 0x9f, 0x39, 0xe4, 0x38, 0x90, 0x34, 0xe7, 0x21, 0xf0, 0xb9, 0xc3, 0x08, 0x6a, 0x2e,
	0xc3, 0x2b, 0x88, 0x7c, 0xe1, 0x2c, 0xdd, 0x57, 0xe5, 0xc8, 0xde, 0x73, 0x8c, 0x3d, 0xa6, 0xa5,
	0x4c, 0xec, 0xab, 0x2e, 0x63, 0x83, 0x44, 0xb6, 0x42, 0x07, 0x94, 0xcb, 0x2c, 0x43, 0xb6, 0xc1,
	0x9e, 0xf0, 0xcc, 0xba, 0x51, 0xe2, 0x32, 0x79, 0x51, 0xdd, 0x1d, 0x75, 0xd1, 0xb6, 0xbc, 0x74,
	0x16, 0x66, 0x32, 0x9c, 0x4e, 0x26, 0xa0, 0xba, 0xfa, 0xaf, 0xe5, 0xf5, 0xbb, 0x2b, 0xab, 0xcc,
	0x37, 0x5b, 0xdc, 0x76, 0xc4, 0xc2, 0xda, 0x1e, 0xc7, 0xc1, 0xe3, 0xe2, 0x4f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0x80, 0x10, 0x6c, 0x49, 0x15, 0x00, 0x00,
}
